language: perl
sudo: false
dist: trusty
cache:
  directories:
    # local::lib caching
    - $HOME/perl5
addons:
  apt:
    packages:
      - libzmq3-dev
      - python3-pygments
      - python3-setuptools
      - aspell     # for dzil Test::PodSpelling
      - aspell-en  # for dzil Test::PodSpelling
perl:
  - "5.14"
  - "5.16"
  - "5.20"
  #- "blead"
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1
    - perl: "system"
      os: osx
before_install:
  - >
      if [ "$TRAVIS_OS_NAME" == "osx" ]; then
        brew install cpanm zmq python3;
      fi
  # Update Python install
  - >
      export PATH=$(python3 -c "import site, os; print(os.path.join(site.USER_BASE, 'bin'))"):$PATH;
      export PYTHONPATH=$(python3 -c "import site; print(site.USER_SITE)")${PYTHONPATH:+:}${PYTHONPATH};
      easy_install3 --user pip;
      pip3 install --user -U setuptools

  - export DEVOPS_BRANCH="master"
  - pip3 install --user -U -r requirements.txt
  - jupyter --version

  - export ALT_ALIEN_ZMQ_BRANCH="master"
  - export RENARD_DEVOPS_HOOK_PRE_PERL="curl https://raw.githubusercontent.com/zmughal-p5CPAN/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest/$ALT_ALIEN_ZMQ_BRANCH/maint/install-zmq-libzmq.pl | perl - -- Alt::Alien::ZMQ::Alien::ZMQ::latest ZMQ::LibZMQ3 Net::Async::ZMQ"

  - export RENARD_DEVOPS_HOOK_PRE_PERL="$RENARD_DEVOPS_HOOK_PRE_PERL; cpanm -n Expect"
  - eval "$(curl https://raw.githubusercontent.com/project-renard/devops/$DEVOPS_BRANCH/script/helper.pl | perl -- | awk '/^#START/,/^#END/ { print > "/dev/stdout"; next } { print > "/dev/stderr"}' )"
branches:
  except:
    - /^wip\//
    - /^blocked/
