language: perl
perl:
  - "5.14"
  - "5.16"
  - "5.20"
  - "blead"
matrix:
  include:
    - perl: "5.20"
      env: COVERAGE=1
before_install:
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev libmagic-dev python-pygments # install deps using apt-get (need to check the Python 3 IPython as well as dev version of IPython
  - sudo apt-get install gnuplot-x11 # so that PDL::Graphics::Gnuplot plugin can be tested
  - sudo pip install -r requirements.txt
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
sudo: true
