language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.20"
  - "blead"
matrix:
  include:
    - perl: 5.20
      env: COVERAGE=1 AUTHOR_TESTING=1
before_install:
  - sudo apt-get update
  - sudo apt-get install ipython ipython-notebook libzmq3-dev libmagic-dev # install deps using apt-get (need to check the Python 3 IPython as well as dev version of IPython
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
sudo: true
