---
abstract: 'Perl language kernel for IPython'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Test::More: 0
  Test::Most: 0
  perl: 5.010
  version: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  File::ShareDir::Install: 0.06
  perl: 5.010
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-IPerl
requires:
  Capture::Tiny: 0
  Devel::REPL: 0
  File::Copy::Recursive: 0
  File::ShareDir::ProjectDistDir: 0
  File::Spec: 0
  File::Temp: 0
  FindBin: 0
  IO::Async::Handle: 0
  IO::Async::Loop: 0
  IO::Handle: 0
  JSON::MaybeXS: 0
  LWP::UserAgent: 0
  List::AllUtils: 0
  Log::Any: 0
  MIME::Base64: 0
  Moo: 0
  Moo::Role: 0
  MooX::HandlesVia: 0
  MooX::Singleton: 0
  MooX::Types::MooseLike::Base: 0
  MooseX::HandlesConstructor: 0
  Path::Class: 0
  Reply: 0
  Reply::Plugin: 0
  Role::Tiny: 0
  Scalar::Util: 0
  Try::Tiny: 0
  UUID::Tiny: 0
  ZMQ::Constants: 0
  ZMQ::LibZMQ3: 0
  autodie: 0
  base: 0
  constant: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/zmughal/p5-Devel-IPerl
  repository: https://github.com/zmughal/p5-Devel-IPerl.git
version: 0.002
