name: Run Tests

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    env:
      ALT_ALIEN_ZMQ_BRANCH: "master"
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        perl: ['5']
        include:
          - { os: 'ubuntu-latest', perl: "5.14" }
          - { os: 'ubuntu-latest', perl: "5.16" }
          - { os: 'ubuntu-latest', perl: "5.20" }
          - { os: 'ubuntu-latest', perl: "5.30" }
          - { os: 'ubuntu-latest', perl: "5.32" }
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        if: runner.os != 'Windows'
        with:
          perl-version: ${{ matrix.perl }}
      - name: Set up perl (Strawberry)
        uses: shogo82148/actions-setup-perl@v1
        if: runner.os == 'Windows'
        with:
          distribution: 'strawberry'

      - run: perl -V

      - name: Install native deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install \
                libzmq3-dev \
                python3-pygments \
                python3-setuptools
      - name: Install native deps
        if: runner.os == 'macOS'
        run: |
          brew install zmq python3

      - name: Install Python deps
        run: |
          pip3 install -r requirements.txt

      - name: Install Perl deps (Windows)
        if: runner.os == 'Windows'
        run: |
          curl https://raw.githubusercontent.com/zmughal-CPAN/p5-Alt-Alien-ZMQ-Alien-ZMQ-latest/${{ env.ALT_ALIEN_ZMQ_BRANCH }}/maint/install-zmq-libzmq.pl | perl - --notest -- Alt::Alien::ZMQ::Alien::ZMQ::latest ZMQ::LibZMQ3 Net::Async::ZMQ
      - name: Install Perl deps
        run: |
          cpanm --notest --installdeps .

      - name: Run tests
        env:
          AUTHOR_TESTING: 1
        run: |
          prove -lvr t/
